"""initial schema with users and tenancy

Revision ID: 2a47c215a114
Revises: 
Create Date: 2026-08-29 02:13:45.591962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2a47c215a114'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agency_audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target', sa.String(length=500), nullable=False),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('adapter_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('principal', sa.String(length=100), nullable=False),
    sa.Column('blob', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'platform', 'principal', name='uq_adapter_credentials_user_platform_principal')
    )
    op.create_index(op.f('ix_adapter_credentials_platform'), 'adapter_credentials', ['platform'], unique=False)
    op.create_index(op.f('ix_adapter_credentials_user_id'), 'adapter_credentials', ['user_id'], unique=False)
    op.create_table('adapter_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'platform', 'key', name='uq_adapter_state_user_platform_key')
    )
    op.create_index(op.f('ix_adapter_state_platform'), 'adapter_state', ['platform'], unique=False)
    op.create_index(op.f('ix_adapter_state_user_id'), 'adapter_state', ['user_id'], unique=False)
    op.create_table('alert_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('realtime_enabled', sa.Boolean(), nullable=False),
    sa.Column('min_score_alert', sa.Float(), nullable=False),
    sa.Column('digest_mode', sa.String(length=10), nullable=False),
    sa.Column('hot_job_enabled', sa.Boolean(), nullable=False),
    sa.Column('hot_job_max_proposals', sa.Integer(), nullable=False),
    sa.Column('hot_job_posted_hours', sa.Integer(), nullable=False),
    sa.Column('hot_job_min_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_alert_settings_user')
    )
    op.create_index(op.f('ix_alert_settings_user_id'), 'alert_settings', ['user_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action_type'), 'audit_log', ['action_type'], unique=False)
    op.create_index(op.f('ix_audit_log_user_id'), 'audit_log', ['user_id'], unique=False)
    op.create_table('competitor_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('category', sa.String(length=200), nullable=False),
    sa.Column('gigs', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('insights', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitor_snapshots_category'), 'competitor_snapshots', ['category'], unique=False)
    op.create_index(op.f('ix_competitor_snapshots_platform'), 'competitor_snapshots', ['platform'], unique=False)
    op.create_index(op.f('ix_competitor_snapshots_user_id'), 'competitor_snapshots', ['user_id'], unique=False)
    op.create_table('gig_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('template_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('auto_publish', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gig_templates_platform'), 'gig_templates', ['platform'], unique=False)
    op.create_index(op.f('ix_gig_templates_user_id'), 'gig_templates', ['user_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=300), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('job_type', sa.String(length=20), nullable=True),
    sa.Column('budget_min', sa.Float(), nullable=True),
    sa.Column('budget_max', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('budget_usd_min', sa.Float(), nullable=True),
    sa.Column('budget_usd_max', sa.Float(), nullable=True),
    sa.Column('experience_level', sa.String(length=20), nullable=True),
    sa.Column('client_info', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('proposals_count', sa.Integer(), nullable=True),
    sa.Column('skills', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('languages', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('work_arrangement', sa.String(length=20), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('apply_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('score_breakdown', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('red_flags', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False),
    sa.Column('duplicate_of', sa.Integer(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'platform', 'external_id', name='uq_jobs_user_platform_external')
    )
    op.create_index(op.f('ix_jobs_external_id'), 'jobs', ['external_id'], unique=False)
    op.create_index(op.f('ix_jobs_platform'), 'jobs', ['platform'], unique=False)
    op.create_index(op.f('ix_jobs_quality_score'), 'jobs', ['quality_score'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index(op.f('ix_jobs_user_id'), 'jobs', ['user_id'], unique=False)
    op.create_table('keyword_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('service_type', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keyword_groups_user_id'), 'keyword_groups', ['user_id'], unique=False)
    op.create_table('platform_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('principal', sa.String(length=100), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('credential_ref', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_accounts_platform'), 'platform_accounts', ['platform'], unique=False)
    op.create_index(op.f('ix_platform_accounts_user_id'), 'platform_accounts', ['user_id'], unique=False)
    op.create_table('portfolio_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_items_user_id'), 'portfolio_items', ['user_id'], unique=False)
    op.create_table('profile_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('pitch_template', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_templates_platform'), 'profile_templates', ['platform'], unique=False)
    op.create_index(op.f('ix_profile_templates_user_id'), 'profile_templates', ['user_id'], unique=False)
    op.create_table('rate_card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('skill_category', sa.String(length=200), nullable=False),
    sa.Column('hourly_rate', sa.Float(), nullable=True),
    sa.Column('fixed_min', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rate_card_user_id'), 'rate_card', ['user_id'], unique=False)
    op.create_table('stealth_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('result', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stealth_tasks_platform'), 'stealth_tasks', ['platform'], unique=False)
    op.create_index(op.f('ix_stealth_tasks_status'), 'stealth_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_stealth_tasks_user_id'), 'stealth_tasks', ['user_id'], unique=False)
    op.create_table('templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('bid', sa.Float(), nullable=True),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('uses', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('win_rate', sa.Float(), nullable=False),
    sa.Column('source_proposal_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_templates_platform'), 'templates', ['platform'], unique=False)
    op.create_index(op.f('ix_templates_user_id'), 'templates', ['user_id'], unique=False)
    op.create_table('gigs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('external_id', sa.String(length=300), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('price_min', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['gig_templates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gigs_platform'), 'gigs', ['platform'], unique=False)
    op.create_index(op.f('ix_gigs_status'), 'gigs', ['status'], unique=False)
    op.create_index(op.f('ix_gigs_user_id'), 'gigs', ['user_id'], unique=False)
    op.create_table('keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('term', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['keyword_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proposal_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('proposal_text', sa.Text(), nullable=False),
    sa.Column('humanized_text', sa.Text(), nullable=False),
    sa.Column('typing_plan', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('bid_amount', sa.Float(), nullable=True),
    sa.Column('bid_period_days', sa.Integer(), nullable=True),
    sa.Column('bid_rationale', sa.String(length=500), nullable=False),
    sa.Column('portfolio_item_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('portfolio_match', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('analysis', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('versions', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rejection_reason', sa.String(length=50), nullable=True),
    sa.Column('rejection_notes', sa.Text(), nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by', sa.String(length=100), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submission_result', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('request_type', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposal_queue_job_id'), 'proposal_queue', ['job_id'], unique=False)
    op.create_index(op.f('ix_proposal_queue_status'), 'proposal_queue', ['status'], unique=False)
    op.create_index(op.f('ix_proposal_queue_user_id'), 'proposal_queue', ['user_id'], unique=False)
    op.create_table('search_filters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('keyword_group_id', sa.Integer(), nullable=True),
    sa.Column('platforms', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('job_types', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('budgets', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('experience_levels', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('client_filters', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('posted_within_hours', sa.Integer(), nullable=True),
    sa.Column('apply_deadline_within_hours', sa.Integer(), nullable=True),
    sa.Column('work_arrangements', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('languages', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('max_proposals', sa.Integer(), nullable=True),
    sa.Column('quality_threshold', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['keyword_group_id'], ['keyword_groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_filters_user_id'), 'search_filters', ['user_id'], unique=False)
    op.create_table('gig_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('gig_id', sa.Integer(), nullable=False),
    sa.Column('week', sa.String(length=10), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('orders', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=False),
    sa.Column('suggestions', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['gig_id'], ['gigs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gig_metrics_gig_id'), 'gig_metrics', ['gig_id'], unique=False)
    op.create_index(op.f('ix_gig_metrics_user_id'), 'gig_metrics', ['user_id'], unique=False)
    op.create_table('rejection_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposal_queue.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rejection_feedback_platform'), 'rejection_feedback', ['platform'], unique=False)
    op.create_index(op.f('ix_rejection_feedback_user_id'), 'rejection_feedback', ['user_id'], unique=False)
    op.create_table('search_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('keyword_group_id', sa.Integer(), nullable=True),
    sa.Column('filter_id', sa.Integer(), nullable=True),
    sa.Column('boolean_query', sa.String(length=1000), nullable=False),
    sa.Column('auto_queue_proposals', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['filter_id'], ['search_filters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['keyword_group_id'], ['keyword_groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_profiles_user_id'), 'search_profiles', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_profiles_user_id'), table_name='search_profiles')
    op.drop_table('search_profiles')
    op.drop_index(op.f('ix_rejection_feedback_user_id'), table_name='rejection_feedback')
    op.drop_index(op.f('ix_rejection_feedback_platform'), table_name='rejection_feedback')
    op.drop_table('rejection_feedback')
    op.drop_index(op.f('ix_gig_metrics_user_id'), table_name='gig_metrics')
    op.drop_index(op.f('ix_gig_metrics_gig_id'), table_name='gig_metrics')
    op.drop_table('gig_metrics')
    op.drop_index(op.f('ix_search_filters_user_id'), table_name='search_filters')
    op.drop_table('search_filters')
    op.drop_index(op.f('ix_proposal_queue_user_id'), table_name='proposal_queue')
    op.drop_index(op.f('ix_proposal_queue_status'), table_name='proposal_queue')
    op.drop_index(op.f('ix_proposal_queue_job_id'), table_name='proposal_queue')
    op.drop_table('proposal_queue')
    op.drop_table('keywords')
    op.drop_index(op.f('ix_gigs_user_id'), table_name='gigs')
    op.drop_index(op.f('ix_gigs_status'), table_name='gigs')
    op.drop_index(op.f('ix_gigs_platform'), table_name='gigs')
    op.drop_table('gigs')
    op.drop_index(op.f('ix_templates_user_id'), table_name='templates')
    op.drop_index(op.f('ix_templates_platform'), table_name='templates')
    op.drop_table('templates')
    op.drop_index(op.f('ix_stealth_tasks_user_id'), table_name='stealth_tasks')
    op.drop_index(op.f('ix_stealth_tasks_status'), table_name='stealth_tasks')
    op.drop_index(op.f('ix_stealth_tasks_platform'), table_name='stealth_tasks')
    op.drop_table('stealth_tasks')
    op.drop_index(op.f('ix_rate_card_user_id'), table_name='rate_card')
    op.drop_table('rate_card')
    op.drop_index(op.f('ix_profile_templates_user_id'), table_name='profile_templates')
    op.drop_index(op.f('ix_profile_templates_platform'), table_name='profile_templates')
    op.drop_table('profile_templates')
    op.drop_index(op.f('ix_portfolio_items_user_id'), table_name='portfolio_items')
    op.drop_table('portfolio_items')
    op.drop_index(op.f('ix_platform_accounts_user_id'), table_name='platform_accounts')
    op.drop_index(op.f('ix_platform_accounts_platform'), table_name='platform_accounts')
    op.drop_table('platform_accounts')
    op.drop_index(op.f('ix_keyword_groups_user_id'), table_name='keyword_groups')
    op.drop_table('keyword_groups')
    op.drop_index(op.f('ix_jobs_user_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_quality_score'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_platform'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_external_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_gig_templates_user_id'), table_name='gig_templates')
    op.drop_index(op.f('ix_gig_templates_platform'), table_name='gig_templates')
    op.drop_table('gig_templates')
    op.drop_index(op.f('ix_competitor_snapshots_user_id'), table_name='competitor_snapshots')
    op.drop_index(op.f('ix_competitor_snapshots_platform'), table_name='competitor_snapshots')
    op.drop_index(op.f('ix_competitor_snapshots_category'), table_name='competitor_snapshots')
    op.drop_table('competitor_snapshots')
    op.drop_index(op.f('ix_audit_log_user_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action_type'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_alert_settings_user_id'), table_name='alert_settings')
    op.drop_table('alert_settings')
    op.drop_index(op.f('ix_adapter_state_user_id'), table_name='adapter_state')
    op.drop_index(op.f('ix_adapter_state_platform'), table_name='adapter_state')
    op.drop_table('adapter_state')
    op.drop_index(op.f('ix_adapter_credentials_user_id'), table_name='adapter_credentials')
    op.drop_index(op.f('ix_adapter_credentials_platform'), table_name='adapter_credentials')
    op.drop_table('adapter_credentials')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('agency_audit_log')
    # ### end Alembic commands ###
