"""Guided and manual tone persistence, real outcome action and next-job reset."""
import os
from playwright.sync_api import sync_playwright, expect

with sync_playwright() as p:
    browser=p.chromium.launch(headless=True)
    page=browser.new_page(viewport={'width':1440,'height':1100})
    errors=[];page.on('pageerror',lambda error:errors.append(str(error)))
    page.on('dialog',lambda dialog:dialog.accept())
    page.goto('http://127.0.0.1:8059/')
    page.get_by_label('Email',exact=True).fill(os.environ['GIGHOUND_UI_REVIEW_EMAIL'])
    page.get_by_label('Password',exact=True).fill(os.environ['GIGHOUND_UI_REVIEW_PASSWORD'])
    page.get_by_role('button',name='Sign in',exact=True).last.click()
    expect(page.get_by_role('heading',name='Guided applications',exact=True)).to_be_visible()
    page.get_by_role('button',name='3. Choose a job',exact=True).click()
    page.locator('article').filter(has=page.get_by_role('heading',name='Synthetic manual review',exact=True)).get_by_role('button').click()
    expect(page.get_by_role('heading',name='Step 4 of 8: Understand & draft')).to_be_visible()
    page.get_by_label('Application tone',exact=True).select_option('diagnostic')
    expect(page.get_by_label('Application tone',exact=True)).to_have_value('diagnostic')
    page.reload()
    expect(page.get_by_role('heading',name='Step 4 of 8: Understand & draft')).to_be_visible()
    expect(page.get_by_label('Application tone',exact=True)).to_have_value('diagnostic')
    page.get_by_role('button',name='8. Record the outcome',exact=True).click()
    page.get_by_text('Synthetic manual review',exact=True).click()
    expect(page.get_by_label('Application tone',exact=True)).to_have_value('diagnostic')
    page.get_by_role('button',name='Hired',exact=True).click()
    expect(page.locator('.pill').filter(has_text='hired')).to_be_visible()
    page.get_by_role('button',name='Start another application',exact=True).click()
    expect(page.get_by_role('heading',name='Step 3 of 8: Choose a job')).to_be_visible()
    expect(page.get_by_text('Current application:',exact=False)).to_have_count(0)
    expect(page.get_by_role('button',name='4. Understand & draft',exact=True)).to_be_disabled()
    page.get_by_label('Start in guided mode when I open GigHound').uncheck()
    expect(page.get_by_label('Start in guided mode when I open GigHound')).not_to_be_checked()
    expect(page.get_by_label('Start in guided mode when I open GigHound')).to_be_enabled()
    page.goto('http://127.0.0.1:8059/')
    expect(page.get_by_role('heading',name='Job Feed',exact=True)).to_be_visible()
    # Manual review sees the same saved, job-specific tone.
    page.goto('http://127.0.0.1:8059/?view=proposals')
    page.locator('select').first.select_option('submitted')
    page.get_by_text('Synthetic manual review',exact=True).click()
    expect(page.get_by_label('Application tone',exact=True)).to_have_value('diagnostic')
    # Hiring briefs can be saved manually without an API key or publication.
    page.goto('http://127.0.0.1:8059/?view=workbench')
    page.get_by_role('button',name='Hiring posts & service ads',exact=True).click()
    page.get_by_label('Post title',exact=True).fill('Synthetic hiring post')
    page.get_by_label('Brief: deliverables, skills, audience, budget and timing',exact=True).fill('Repair invoice rounding and supply reproducible regression examples.')
    page.get_by_label('Post draft',exact=True).fill('Seeking help with invoice rounding. Budget to confirm.')
    page.get_by_role('button',name='Create record',exact=True).click()
    expect(page.get_by_role('heading',name='Synthetic hiring post',exact=False)).to_be_visible()
    page.reload()
    page.get_by_role('button',name='Hiring posts & service ads',exact=True).click()
    expect(page.get_by_text('Seeking help with invoice rounding. Budget to confirm.',exact=True)).to_be_visible()
    page.goto('http://127.0.0.1:8059/?view=gigs')
    page.get_by_label('Title',exact=True).fill('Synthetic registered gig')
    page.get_by_label('URL',exact=True).fill('https://example.test/synthetic-gig')
    page.get_by_label('Price min',exact=True).fill('49.99')
    page.get_by_role('button',name='Register',exact=True).click()
    expect(page.get_by_role('cell',name='Synthetic registered gig',exact=True)).to_be_visible()
    page.reload()
    expect(page.get_by_role('cell',name='Synthetic registered gig',exact=True)).to_be_visible()
    expect(page.get_by_role('cell',name='49.99',exact=False)).to_be_visible()
    assert not errors,errors
    browser.close()
print('PASS: first-load wizard, resume, shared tone, recorded synthetic hire, fresh application reset, manual startup preference and saved hiring draft')
